language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r src/2_Backend/requirements.txt
  - cd src/iptables
  - make
  - cd ../../
script:
  - cd src
  - cd 2_Backend
  - python -m unittest test.py
notifications:
  slack: leighton-personal:qDniIaHsJ8P86IzoW1LBHN8p
