language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - build-essential 
    - libpcre3-dev
    - swig
    - libpython3-dev
    - python3-dev
    - python-pip
install:
  - pip install -r src/2_Backend/requirements.txt
  - cd src/iptables
  - make travis
  - cd ../../
script:
  - cd src
  - cd 2_Backend
  - python test.py
notifications:
  slack: leighton-personal:qDniIaHsJ8P86IzoW1LBHN8p
